### PR TITLE
changes for r1.0

### PR DESCRIPTION
**Pull request by arpit15**
Make minor changes to make it compatible to r1.0

### CODE REVIEW

**Comment by miyosuda** [comment]
@arpit15 
Thank you for the contribution!
I'm now testing your tf1.0 PR in `dev` branch, but the score didn't increase like before with seekavoid01 in my environment.

Do we need to change anything more for r1.0?
I'll investigate this! Thanks!

unreal_r1 0_score

**Comment by arpit15** [comment]
@miyosuda  Please check the master or r1.0 branch. I made the test on seekavoid arena with the same parameters. Here is the [graph](https://github.com/arpit15/unreal/blob/r1.0/doc/graph_seekavoid_01.png)

**Comment by miyosuda** [comment]
I see, thanks!
I'll try again with your setting.

**Comment by miyosuda** [comment]
@arpit15 
I tried again with your setting and got score like this. Thanks! I merged it to master.

graph_seekavoid_01

**Pull request closed without merging**
